const repositoryUrl = "https://github.com/davidtrotonda/link-my-app";
const licenseUrl = `${repositoryUrl}/blob/main/LICENSE`;

export const openSourceLinks = {
  repository: repositoryUrl,
  license: licenseUrl,
  repositoryUrl,
  licenseUrl,
};

export const openSourceContent = {
  en: {
    metaTitle: "Open Source Smart Link for App Store and Google Play",
    metaDescription: "Create or self-host an Apache-2.0 open-source smart link for App Store, Google Play, web fallback, QR codes and click analytics.",
    title: "Open-source smart links for App Store and Google Play",
    intro: "Link My App turns the App Store URL, Google Play URL and a fallback website into one clean link. The complete source code is public under Apache 2.0, so you can use the hosted service or deploy it on your own infrastructure.",
    repoButton: "View source code",
    createButton: "Create a free smart link",
    facts: [
      { title: "Public repository", text: "Inspect the source, follow changes, report issues and contribute on GitHub." },
      { title: "Apache 2.0", text: "Use, modify and redistribute the project while keeping the license and notices." },
      { title: "Self-hostable", text: "Deploy the React app, Firebase services and Cloudflare redirect layer yourself." },
      { title: "Hosted version", text: "Use link-my.app immediately without maintaining servers or redirect infrastructure." },
    ],
    choiceTitle: "Use it your way",
    choiceIntro: "The public product and the source repository solve the same core problem: one app-download URL for every device.",
    hostedTitle: "Hosted by Link My App",
    hostedText: "Create smart links and QR codes in minutes. We operate the redirect layer, dashboard and analytics so you can focus on promoting your app.",
    selfHostedTitle: "Deploy it yourself",
    selfHostedText: "Clone the repository, connect your own Firebase and Cloudflare accounts and keep control of the deployment, domain and data configuration.",
    howTitle: "What the open-source project includes",
    steps: [
      { title: "Smart routing", text: "Detect iPhone, Android and desktop traffic and send every visitor to the correct destination." },
      { title: "Creator dashboard", text: "Create, edit, pause and measure smart links, QR codes, sources and campaigns." },
      { title: "Production architecture", text: "React and Vite on the frontend, Firebase for authentication and data, and Cloudflare Workers at the edge." },
    ],
    transparencyTitle: "Built in public",
    transparencyText: "The repository contains the application, redirect Worker, database rules, deployment scripts and technical documentation. Private production credentials, customer data and service secrets are never published.",
    stackTitle: "Technology you can inspect",
    stack: ["React 19 + Vite", "Firebase Authentication and Realtime Database", "Cloudflare Workers, KV and D1", "Stripe functions and webhooks"],
    licenseTitle: "A clear open-source license",
    licenseText: "Apache License 2.0 allows commercial use, modification and distribution and includes an express patent grant. Copies and derivative works must preserve the license and required notices.",
    licenseButton: "Read the Apache 2.0 license",
    faqTitle: "Open-source questions",
    faqs: [
      { question: "Is Link My App really open source?", answer: "Yes. The official repository is public and the project is released under Apache License 2.0." },
      { question: "Can I self-host it?", answer: "Yes. The repository documents the React, Firebase and Cloudflare setup needed to run your own deployment." },
      { question: "Do I have to self-host it?", answer: "No. You can use the hosted version at link-my.app and create smart links without operating the infrastructure." },
      { question: "Can a company use the code?", answer: "Apache 2.0 permits commercial use, modification and distribution as long as its license and notice requirements are respected." },
    ],
    ctaTitle: "One smart link, with code you can verify",
    ctaText: "Start with the hosted version or explore the repository and deploy Link My App your way.",
  },
  es: {
    metaTitle: "Smart links de código abierto para App Store y Google Play",
    metaDescription: "Crea o autoaloja un smart link open source Apache 2.0 para App Store, Google Play, web alternativa, códigos QR y analítica de clics.",
    title: "El smart link de código abierto para App Store y Google Play",
    intro: "Link My App convierte la URL de App Store, la de Google Play y una web alternativa en un único enlace. Todo el código fuente es público bajo Apache 2.0: puedes usar el servicio alojado o desplegarlo en tu propia infraestructura.",
    repoButton: "Ver código fuente",
    createButton: "Crear un smart link gratis",
    facts: [
      { title: "Repositorio público", text: "Revisa el código, consulta los cambios, comunica incidencias y contribuye en GitHub." },
      { title: "Apache 2.0", text: "Usa, modifica y redistribuye el proyecto conservando la licencia y los avisos." },
      { title: "Autoalojable", text: "Despliega por tu cuenta la app React, los servicios Firebase y la capa de redirección Cloudflare." },
      { title: "Versión alojada", text: "Usa link-my.app al instante sin mantener servidores ni infraestructura de redirección." },
    ],
    choiceTitle: "Úsalo como prefieras",
    choiceIntro: "El producto público y el repositorio resuelven el mismo problema: una sola URL de descarga para cualquier dispositivo.",
    hostedTitle: "Alojado por Link My App",
    hostedText: "Crea smart links y códigos QR en minutos. Nosotros gestionamos las redirecciones, el panel y la analítica para que promociones tu app.",
    selfHostedTitle: "Despliégalo tú mismo",
    selfHostedText: "Clona el repositorio, conecta tus cuentas de Firebase y Cloudflare y conserva el control del despliegue, el dominio y los datos.",
    howTitle: "Qué incluye el proyecto open source",
    steps: [
      { title: "Enrutamiento inteligente", text: "Detecta tráfico de iPhone, Android y ordenador y envía cada visita al destino correcto." },
      { title: "Panel para creadores", text: "Crea, edita, pausa y mide smart links, códigos QR, fuentes y campañas." },
      { title: "Arquitectura de producción", text: "React y Vite en el frontend, Firebase para autenticación y datos y Cloudflare Workers en el edge." },
    ],
    transparencyTitle: "Desarrollado de forma pública",
    transparencyText: "El repositorio contiene la aplicación, el Worker de redirección, las reglas de base de datos, scripts de despliegue y documentación técnica. Las credenciales privadas, los datos de clientes y los secretos de producción nunca se publican.",
    stackTitle: "Tecnología que puedes revisar",
    stack: ["React 19 + Vite", "Firebase Authentication y Realtime Database", "Cloudflare Workers, KV y D1", "Funciones y webhooks de Stripe"],
    licenseTitle: "Una licencia open source clara",
    licenseText: "Apache 2.0 permite uso comercial, modificación y distribución e incluye una concesión expresa de patentes. Las copias y obras derivadas deben conservar la licencia y los avisos exigidos.",
    licenseButton: "Leer la licencia Apache 2.0",
    faqTitle: "Preguntas sobre el código abierto",
    faqs: [
      { question: "¿Link My App es realmente open source?", answer: "Sí. El repositorio oficial es público y el proyecto se distribuye con licencia Apache 2.0." },
      { question: "¿Puedo alojarlo en mis servidores?", answer: "Sí. El repositorio documenta la configuración de React, Firebase y Cloudflare necesaria para ejecutar tu propio despliegue." },
      { question: "¿Tengo que autoalojarlo?", answer: "No. Puedes usar la versión alojada en link-my.app y crear smart links sin gestionar infraestructura." },
      { question: "¿Puede una empresa utilizar el código?", answer: "Apache 2.0 permite el uso comercial, la modificación y la distribución respetando sus requisitos de licencia y atribución." },
    ],
    ctaTitle: "Un smart link con código que puedes verificar",
    ctaText: "Empieza con la versión alojada o explora el repositorio y despliega Link My App como prefieras.",
  },
  fr: {
    metaTitle: "Smart link open source pour App Store et Google Play",
    metaDescription: "Crée ou auto-héberge un smart link open source Apache 2.0 pour App Store, Google Play, site alternatif, QR codes et statistiques.",
    title: "Le smart link open source pour App Store et Google Play",
    intro: "Link My App réunit l’URL App Store, l’URL Google Play et un site alternatif dans un seul lien. Tout le code source est public sous licence Apache 2.0 : utilise le service hébergé ou déploie-le sur ta propre infrastructure.",
    repoButton: "Voir le code source",
    createButton: "Créer un smart link gratuit",
    facts: [
      { title: "Dépôt public", text: "Consulte le code, suis les changements, signale des problèmes et contribue sur GitHub." },
      { title: "Apache 2.0", text: "Utilise, modifie et redistribue le projet en conservant la licence et les mentions." },
      { title: "Auto-hébergeable", text: "Déploie toi-même l’app React, les services Firebase et la couche de redirection Cloudflare." },
      { title: "Version hébergée", text: "Utilise link-my.app immédiatement sans gérer de serveurs ni d’infrastructure de redirection." },
    ],
    choiceTitle: "Utilise-le à ta façon",
    choiceIntro: "Le produit public et le dépôt résolvent le même problème : une seule URL de téléchargement pour tous les appareils.",
    hostedTitle: "Hébergé par Link My App",
    hostedText: "Crée des smart links et des QR codes en quelques minutes. Nous gérons les redirections, le tableau de bord et les statistiques.",
    selfHostedTitle: "Déploie-le toi-même",
    selfHostedText: "Clone le dépôt, connecte tes comptes Firebase et Cloudflare et garde le contrôle du déploiement, du domaine et des données.",
    howTitle: "Ce que comprend le projet open source",
    steps: [
      { title: "Routage intelligent", text: "Détecte iPhone, Android et ordinateur puis envoie chaque visite vers la bonne destination." },
      { title: "Tableau de bord", text: "Crée, modifie, mets en pause et mesure les smart links, QR codes, sources et campagnes." },
      { title: "Architecture de production", text: "React et Vite côté frontend, Firebase pour l’authentification et les données, Cloudflare Workers en périphérie." },
    ],
    transparencyTitle: "Développé publiquement",
    transparencyText: "Le dépôt contient l’application, le Worker de redirection, les règles de base de données, les scripts de déploiement et la documentation. Les identifiants privés, données clients et secrets de production ne sont jamais publiés.",
    stackTitle: "Une technologie vérifiable",
    stack: ["React 19 + Vite", "Firebase Authentication et Realtime Database", "Cloudflare Workers, KV et D1", "Fonctions et webhooks Stripe"],
    licenseTitle: "Une licence open source claire",
    licenseText: "Apache 2.0 autorise l’usage commercial, la modification et la distribution et comprend une concession expresse de brevets. Les copies doivent conserver la licence et les mentions requises.",
    licenseButton: "Lire la licence Apache 2.0",
    faqTitle: "Questions sur l’open source",
    faqs: [
      { question: "Link My App est-il vraiment open source ?", answer: "Oui. Le dépôt officiel est public et le projet est publié sous licence Apache 2.0." },
      { question: "Puis-je l’auto-héberger ?", answer: "Oui. Le dépôt documente la configuration React, Firebase et Cloudflare nécessaire à ton propre déploiement." },
      { question: "Dois-je l’auto-héberger ?", answer: "Non. Tu peux utiliser la version hébergée sur link-my.app sans gérer l’infrastructure." },
      { question: "Une entreprise peut-elle utiliser le code ?", answer: "Apache 2.0 autorise l’usage commercial, la modification et la distribution si ses obligations sont respectées." },
    ],
    ctaTitle: "Un smart link dont tu peux vérifier le code",
    ctaText: "Commence avec la version hébergée ou explore le dépôt et déploie Link My App à ta façon.",
  },
  ja: {
    metaTitle: "App Store・Google Play対応オープンソーススマートリンク",
    metaDescription: "Apache 2.0のオープンソースで、App Store、Google Play、Web、QRコード、クリック分析に対応するスマートリンクを作成・セルフホストできます。",
    title: "App StoreとGoogle Playのためのオープンソース・スマートリンク",
    intro: "Link My Appは、App Store、Google Play、代替WebサイトのURLを1つのリンクにまとめます。ソースコードはApache 2.0で公開されており、ホスト版を使うことも、自分の環境にデプロイすることもできます。",
    repoButton: "ソースコードを見る",
    createButton: "無料スマートリンクを作成",
    facts: [
      { title: "公開リポジトリ", text: "GitHubでコード確認、変更履歴、問題報告、コントリビューションができます。" },
      { title: "Apache 2.0", text: "ライセンスと通知を保持すれば、利用・変更・再配布できます。" },
      { title: "セルフホスト可能", text: "Reactアプリ、Firebaseサービス、Cloudflareのリダイレクト層を自分でデプロイできます。" },
      { title: "ホスト版", text: "サーバー管理なしでlink-my.appをすぐに利用できます。" },
    ],
    choiceTitle: "目的に合わせて利用",
    choiceIntro: "公開サービスとソースリポジトリは、どの端末にも対応する1つのアプリダウンロードURLを提供します。",
    hostedTitle: "Link My Appによるホスティング",
    hostedText: "数分でスマートリンクとQRコードを作成。リダイレクト、ダッシュボード、分析は私たちが運用します。",
    selfHostedTitle: "自分でデプロイ",
    selfHostedText: "リポジトリをクローンし、自分のFirebaseとCloudflareを接続して、ドメインやデータを管理できます。",
    howTitle: "オープンソース版に含まれるもの",
    steps: [
      { title: "スマートルーティング", text: "iPhone、Android、PCを判定し、各ユーザーを正しいリンク先へ送ります。" },
      { title: "管理ダッシュボード", text: "スマートリンク、QR、流入元、キャンペーンを作成・編集・停止・計測できます。" },
      { title: "本番向けアーキテクチャ", text: "ReactとVite、Firebase認証・データ、Cloudflare Workersで構成されています。" },
    ],
    transparencyTitle: "公開開発",
    transparencyText: "リポジトリにはアプリ、リダイレクトWorker、データベースルール、デプロイスクリプト、技術文書が含まれます。秘密鍵、顧客データ、本番シークレットは公開されません。",
    stackTitle: "確認できる技術スタック",
    stack: ["React 19 + Vite", "Firebase Authentication・Realtime Database", "Cloudflare Workers、KV、D1", "Stripe Functions・Webhooks"],
    licenseTitle: "明確なオープンソースライセンス",
    licenseText: "Apache 2.0は商用利用、変更、配布を許可し、明示的な特許許諾を含みます。コピーや派生物にはライセンスと必要な通知を残してください。",
    licenseButton: "Apache 2.0ライセンスを読む",
    faqTitle: "オープンソースに関する質問",
    faqs: [
      { question: "Link My Appは本当にオープンソースですか？", answer: "はい。公式リポジトリは公開され、Apache 2.0ライセンスで提供されています。" },
      { question: "セルフホストできますか？", answer: "はい。React、Firebase、Cloudflareを使ったデプロイ方法をリポジトリで説明しています。" },
      { question: "セルフホストは必須ですか？", answer: "いいえ。link-my.appのホスト版をそのまま利用できます。" },
      { question: "企業でも利用できますか？", answer: "はい。Apache 2.0の条件を守れば、商用利用、変更、配布が可能です。" },
    ],
    ctaTitle: "検証できるコードで、1つのスマートリンクを",
    ctaText: "ホスト版を今すぐ使うか、リポジトリから自分の環境へデプロイできます。",
  },
  de: {
    metaTitle: "Open-Source-Smartlink für App Store und Google Play",
    metaDescription: "Erstelle oder hoste einen Apache-2.0-Smartlink für App Store, Google Play, Web-Fallback, QR-Codes und Klick-Analytics selbst.",
    title: "Der Open-Source-Smartlink für App Store und Google Play",
    intro: "Link My App verbindet App Store, Google Play und eine alternative Website in einem einzigen Link. Der vollständige Quellcode ist unter Apache 2.0 öffentlich: Nutze den gehosteten Dienst oder betreibe ihn in deiner eigenen Infrastruktur.",
    repoButton: "Quellcode ansehen",
    createButton: "Kostenlosen Smartlink erstellen",
    facts: [
      { title: "Öffentliches Repository", text: "Prüfe den Code, verfolge Änderungen, melde Probleme und wirke auf GitHub mit." },
      { title: "Apache 2.0", text: "Nutze, ändere und verteile das Projekt unter Beibehaltung von Lizenz und Hinweisen." },
      { title: "Selbst hostbar", text: "Betreibe React-App, Firebase-Dienste und Cloudflare-Weiterleitungen selbst." },
      { title: "Gehostete Version", text: "Nutze link-my.app sofort, ohne Server oder Redirect-Infrastruktur zu warten." },
    ],
    choiceTitle: "Nutze es auf deine Weise",
    choiceIntro: "Produkt und Repository lösen dasselbe Problem: eine App-Download-URL für jedes Gerät.",
    hostedTitle: "Von Link My App gehostet",
    hostedText: "Erstelle Smartlinks und QR-Codes in Minuten. Wir betreiben Weiterleitungen, Dashboard und Analytics.",
    selfHostedTitle: "Selbst bereitstellen",
    selfHostedText: "Klone das Repository, verbinde Firebase und Cloudflare und behalte Kontrolle über Deployment, Domain und Daten.",
    howTitle: "Das Open-Source-Projekt enthält",
    steps: [
      { title: "Intelligentes Routing", text: "Erkennt iPhone, Android und Desktop und sendet jeden Besucher zum richtigen Ziel." },
      { title: "Creator-Dashboard", text: "Erstelle, bearbeite, pausiere und analysiere Smartlinks, QR-Codes, Quellen und Kampagnen." },
      { title: "Produktionsarchitektur", text: "React und Vite im Frontend, Firebase für Anmeldung und Daten, Cloudflare Workers am Edge." },
    ],
    transparencyTitle: "Öffentlich entwickelt",
    transparencyText: "Das Repository enthält App, Redirect-Worker, Datenbankregeln, Deployment-Skripte und technische Dokumentation. Private Zugangsdaten, Kundendaten und Produktionsgeheimnisse werden nie veröffentlicht.",
    stackTitle: "Überprüfbare Technologie",
    stack: ["React 19 + Vite", "Firebase Authentication und Realtime Database", "Cloudflare Workers, KV und D1", "Stripe Functions und Webhooks"],
    licenseTitle: "Eine klare Open-Source-Lizenz",
    licenseText: "Apache 2.0 erlaubt kommerzielle Nutzung, Änderungen und Verteilung und enthält eine ausdrückliche Patentlizenz. Kopien müssen Lizenz und erforderliche Hinweise bewahren.",
    licenseButton: "Apache-2.0-Lizenz lesen",
    faqTitle: "Fragen zu Open Source",
    faqs: [
      { question: "Ist Link My App wirklich Open Source?", answer: "Ja. Das offizielle Repository ist öffentlich und steht unter Apache 2.0." },
      { question: "Kann ich es selbst hosten?", answer: "Ja. Das Repository dokumentiert die Einrichtung mit React, Firebase und Cloudflare." },
      { question: "Muss ich es selbst hosten?", answer: "Nein. Du kannst die gehostete Version auf link-my.app ohne eigene Infrastruktur nutzen." },
      { question: "Darf ein Unternehmen den Code nutzen?", answer: "Ja. Apache 2.0 erlaubt kommerzielle Nutzung, Änderung und Verteilung unter Einhaltung der Lizenzbedingungen." },
    ],
    ctaTitle: "Ein Smartlink mit überprüfbarem Code",
    ctaText: "Starte mit der gehosteten Version oder erkunde das Repository und betreibe Link My App selbst.",
  },
  pt: {
    metaTitle: "Smart link open source para App Store e Google Play",
    metaDescription: "Cria ou aloja um smart link open source Apache 2.0 para App Store, Google Play, web alternativa, QR codes e analytics de cliques.",
    title: "O smart link open source para App Store e Google Play",
    intro: "O Link My App junta as URLs da App Store, Google Play e de um site alternativo num único link. Todo o código é público sob Apache 2.0: usa o serviço alojado ou instala-o na tua própria infraestrutura.",
    repoButton: "Ver código fonte",
    createButton: "Criar smart link grátis",
    facts: [
      { title: "Repositório público", text: "Revê o código, acompanha alterações, reporta problemas e contribui no GitHub." },
      { title: "Apache 2.0", text: "Usa, modifica e redistribui o projeto mantendo a licença e os avisos." },
      { title: "Autoalojável", text: "Instala a app React, os serviços Firebase e a camada de redirecionamento Cloudflare." },
      { title: "Versão alojada", text: "Usa link-my.app de imediato sem manter servidores ou infraestrutura de redirecionamento." },
    ],
    choiceTitle: "Usa como preferires",
    choiceIntro: "O produto público e o repositório resolvem o mesmo problema: uma URL de download para todos os dispositivos.",
    hostedTitle: "Alojado pelo Link My App",
    hostedText: "Cria smart links e QR codes em minutos. Gerimos redirecionamentos, painel e analytics para promoveres a tua app.",
    selfHostedTitle: "Instala tu mesmo",
    selfHostedText: "Clona o repositório, liga as tuas contas Firebase e Cloudflare e controla o deployment, domínio e dados.",
    howTitle: "O que inclui o projeto open source",
    steps: [
      { title: "Roteamento inteligente", text: "Deteta iPhone, Android e desktop e envia cada visita para o destino correto." },
      { title: "Painel para criadores", text: "Cria, edita, pausa e mede smart links, QR codes, origens e campanhas." },
      { title: "Arquitetura de produção", text: "React e Vite no frontend, Firebase para autenticação e dados e Cloudflare Workers no edge." },
    ],
    transparencyTitle: "Desenvolvido em público",
    transparencyText: "O repositório contém a aplicação, o Worker de redirecionamento, regras da base de dados, scripts de deployment e documentação. Credenciais privadas, dados de clientes e segredos de produção nunca são publicados.",
    stackTitle: "Tecnologia que podes verificar",
    stack: ["React 19 + Vite", "Firebase Authentication e Realtime Database", "Cloudflare Workers, KV e D1", "Funções e webhooks Stripe"],
    licenseTitle: "Uma licença open source clara",
    licenseText: "Apache 2.0 permite uso comercial, modificação e distribuição e inclui uma concessão expressa de patentes. Cópias e derivados devem manter a licença e os avisos exigidos.",
    licenseButton: "Ler a licença Apache 2.0",
    faqTitle: "Perguntas sobre open source",
    faqs: [
      { question: "O Link My App é mesmo open source?", answer: "Sim. O repositório oficial é público e o projeto usa a licença Apache 2.0." },
      { question: "Posso alojá-lo eu mesmo?", answer: "Sim. O repositório documenta a configuração React, Firebase e Cloudflare para o teu deployment." },
      { question: "Tenho de o autoalojar?", answer: "Não. Podes usar a versão alojada em link-my.app sem gerir infraestrutura." },
      { question: "Uma empresa pode usar o código?", answer: "Sim. Apache 2.0 permite uso comercial, alteração e distribuição respeitando a licença." },
    ],
    ctaTitle: "Um smart link com código verificável",
    ctaText: "Começa com a versão alojada ou explora o repositório e instala o Link My App à tua maneira.",
  },
  it: {
    metaTitle: "Smart link open source per App Store e Google Play",
    metaDescription: "Crea o ospita uno smart link open source Apache 2.0 per App Store, Google Play, sito alternativo, QR code e analisi dei clic.",
    title: "Lo smart link open source per App Store e Google Play",
    intro: "Link My App unisce gli URL di App Store, Google Play e di un sito alternativo in un solo link. Il codice sorgente è pubblico con licenza Apache 2.0: usa il servizio ospitato oppure distribuiscilo sulla tua infrastruttura.",
    repoButton: "Vedi il codice sorgente",
    createButton: "Crea uno smart link gratis",
    facts: [
      { title: "Repository pubblico", text: "Controlla il codice, segui le modifiche, segnala problemi e contribuisci su GitHub." },
      { title: "Apache 2.0", text: "Usa, modifica e ridistribuisci il progetto mantenendo licenza e avvisi." },
      { title: "Self-hosted", text: "Distribuisci in autonomia app React, servizi Firebase e livello di redirect Cloudflare." },
      { title: "Versione ospitata", text: "Usa subito link-my.app senza gestire server o infrastruttura di redirect." },
    ],
    choiceTitle: "Usalo come preferisci",
    choiceIntro: "Il prodotto pubblico e il repository risolvono lo stesso problema: un URL di download per ogni dispositivo.",
    hostedTitle: "Ospitato da Link My App",
    hostedText: "Crea smart link e QR code in pochi minuti. Gestiamo redirect, pannello e analisi per permetterti di promuovere la tua app.",
    selfHostedTitle: "Distribuiscilo tu",
    selfHostedText: "Clona il repository, collega Firebase e Cloudflare e mantieni il controllo su deployment, dominio e dati.",
    howTitle: "Cosa include il progetto open source",
    steps: [
      { title: "Routing intelligente", text: "Riconosce iPhone, Android e desktop e invia ogni visita alla destinazione corretta." },
      { title: "Pannello creator", text: "Crea, modifica, sospendi e misura smart link, QR code, fonti e campagne." },
      { title: "Architettura di produzione", text: "React e Vite nel frontend, Firebase per autenticazione e dati, Cloudflare Workers all’edge." },
    ],
    transparencyTitle: "Sviluppato pubblicamente",
    transparencyText: "Il repository contiene applicazione, Worker di redirect, regole database, script di deployment e documentazione. Credenziali private, dati clienti e segreti di produzione non vengono mai pubblicati.",
    stackTitle: "Tecnologia verificabile",
    stack: ["React 19 + Vite", "Firebase Authentication e Realtime Database", "Cloudflare Workers, KV e D1", "Funzioni e webhook Stripe"],
    licenseTitle: "Una licenza open source chiara",
    licenseText: "Apache 2.0 consente uso commerciale, modifica e distribuzione e include una concessione esplicita di brevetti. Copie e derivati devono conservare licenza e avvisi richiesti.",
    licenseButton: "Leggi la licenza Apache 2.0",
    faqTitle: "Domande sull’open source",
    faqs: [
      { question: "Link My App è davvero open source?", answer: "Sì. Il repository ufficiale è pubblico e il progetto è distribuito con licenza Apache 2.0." },
      { question: "Posso ospitarlo autonomamente?", answer: "Sì. Il repository documenta la configurazione React, Firebase e Cloudflare per il tuo deployment." },
      { question: "Devo fare self-hosting?", answer: "No. Puoi usare la versione ospitata su link-my.app senza gestire infrastruttura." },
      { question: "Un’azienda può usare il codice?", answer: "Sì. Apache 2.0 consente uso commerciale, modifica e distribuzione rispettando la licenza." },
    ],
    ctaTitle: "Uno smart link con codice verificabile",
    ctaText: "Inizia con la versione ospitata o esplora il repository e distribuisci Link My App come preferisci.",
  },
  ko: {
    metaTitle: "App Store·Google Play 오픈 소스 스마트 링크",
    metaDescription: "Apache 2.0 오픈 소스로 App Store, Google Play, 대체 웹, QR 코드, 클릭 분석 스마트 링크를 만들거나 직접 호스팅하세요.",
    title: "App Store와 Google Play를 위한 오픈 소스 스마트 링크",
    intro: "Link My App은 App Store, Google Play, 대체 웹사이트 URL을 하나의 링크로 통합합니다. 전체 소스 코드는 Apache 2.0으로 공개되어 있어 호스팅 서비스를 사용하거나 자체 인프라에 배포할 수 있습니다.",
    repoButton: "소스 코드 보기",
    createButton: "무료 스마트 링크 만들기",
    facts: [
      { title: "공개 저장소", text: "GitHub에서 코드를 검토하고 변경 사항, 이슈, 기여 내용을 확인할 수 있습니다." },
      { title: "Apache 2.0", text: "라이선스와 고지를 유지하면 사용, 수정, 재배포할 수 있습니다." },
      { title: "셀프 호스팅", text: "React 앱, Firebase 서비스, Cloudflare 리디렉션 계층을 직접 배포할 수 있습니다." },
      { title: "호스팅 버전", text: "서버나 리디렉션 인프라 관리 없이 link-my.app을 바로 사용하세요." },
    ],
    choiceTitle: "원하는 방식으로 사용",
    choiceIntro: "공개 서비스와 저장소 모두 모든 기기에 맞는 하나의 앱 다운로드 URL을 제공합니다.",
    hostedTitle: "Link My App 호스팅",
    hostedText: "몇 분 안에 스마트 링크와 QR 코드를 만드세요. 리디렉션, 대시보드, 분석은 Link My App이 운영합니다.",
    selfHostedTitle: "직접 배포",
    selfHostedText: "저장소를 복제하고 Firebase와 Cloudflare를 연결해 배포, 도메인, 데이터를 직접 관리하세요.",
    howTitle: "오픈 소스 프로젝트 구성",
    steps: [
      { title: "스마트 라우팅", text: "iPhone, Android, 데스크톱을 감지해 각 방문자를 올바른 목적지로 보냅니다." },
      { title: "크리에이터 대시보드", text: "스마트 링크, QR 코드, 유입 경로, 캠페인을 생성·수정·중지·분석합니다." },
      { title: "프로덕션 아키텍처", text: "React와 Vite, Firebase 인증과 데이터, Cloudflare Workers로 구성됩니다." },
    ],
    transparencyTitle: "공개 개발",
    transparencyText: "저장소에는 앱, 리디렉션 Worker, 데이터베이스 규칙, 배포 스크립트, 기술 문서가 포함됩니다. 비공개 인증 정보, 고객 데이터, 프로덕션 시크릿은 공개하지 않습니다.",
    stackTitle: "검토 가능한 기술",
    stack: ["React 19 + Vite", "Firebase Authentication·Realtime Database", "Cloudflare Workers, KV, D1", "Stripe Functions·Webhooks"],
    licenseTitle: "명확한 오픈 소스 라이선스",
    licenseText: "Apache 2.0은 상업적 이용, 수정, 배포를 허용하고 명시적 특허 허여를 포함합니다. 복사본과 파생물에는 라이선스와 필수 고지를 유지해야 합니다.",
    licenseButton: "Apache 2.0 라이선스 읽기",
    faqTitle: "오픈 소스 질문",
    faqs: [
      { question: "Link My App은 정말 오픈 소스인가요?", answer: "네. 공식 저장소가 공개되어 있고 Apache 2.0 라이선스로 배포됩니다." },
      { question: "직접 호스팅할 수 있나요?", answer: "네. 저장소에 React, Firebase, Cloudflare 배포 설정이 문서화되어 있습니다." },
      { question: "반드시 직접 호스팅해야 하나요?", answer: "아닙니다. 인프라 관리 없이 link-my.app 호스팅 버전을 사용할 수 있습니다." },
      { question: "기업도 코드를 사용할 수 있나요?", answer: "네. Apache 2.0 조건을 준수하면 상업적 이용, 수정, 배포가 가능합니다." },
    ],
    ctaTitle: "검증 가능한 코드로 만드는 하나의 스마트 링크",
    ctaText: "호스팅 버전을 시작하거나 저장소를 살펴보고 원하는 방식으로 Link My App을 배포하세요.",
  },
  nl: {
    metaTitle: "Open-source smartlink voor App Store en Google Play",
    metaDescription: "Maak of self-host een Apache-2.0-smartlink voor App Store, Google Play, webfallback, QR-codes en klikstatistieken.",
    title: "De open-source smartlink voor App Store en Google Play",
    intro: "Link My App combineert de App Store-URL, Google Play-URL en een alternatieve website in één link. De volledige broncode is openbaar onder Apache 2.0: gebruik de gehoste dienst of implementeer hem op je eigen infrastructuur.",
    repoButton: "Bekijk de broncode",
    createButton: "Maak een gratis smartlink",
    facts: [
      { title: "Openbare repository", text: "Controleer de code, volg wijzigingen, meld problemen en draag bij via GitHub." },
      { title: "Apache 2.0", text: "Gebruik, wijzig en verspreid het project met behoud van licentie en kennisgevingen." },
      { title: "Zelf te hosten", text: "Implementeer zelf de React-app, Firebase-diensten en Cloudflare-redirectlaag." },
      { title: "Gehoste versie", text: "Gebruik link-my.app direct zonder servers of redirectinfrastructuur te beheren." },
    ],
    choiceTitle: "Gebruik het op jouw manier",
    choiceIntro: "Het publieke product en de repository lossen hetzelfde probleem op: één app-download-URL voor elk apparaat.",
    hostedTitle: "Gehost door Link My App",
    hostedText: "Maak binnen enkele minuten smartlinks en QR-codes. Wij beheren redirects, dashboard en statistieken.",
    selfHostedTitle: "Zelf implementeren",
    selfHostedText: "Kloon de repository, verbind Firebase en Cloudflare en houd controle over implementatie, domein en gegevens.",
    howTitle: "Wat het open-source project bevat",
    steps: [
      { title: "Slimme routering", text: "Herkent iPhone, Android en desktop en stuurt elke bezoeker naar de juiste bestemming." },
      { title: "Creator-dashboard", text: "Maak, bewerk, pauzeer en meet smartlinks, QR-codes, bronnen en campagnes." },
      { title: "Productiearchitectuur", text: "React en Vite voor de frontend, Firebase voor authenticatie en data, Cloudflare Workers aan de edge." },
    ],
    transparencyTitle: "Openbaar ontwikkeld",
    transparencyText: "De repository bevat de app, redirect-Worker, databaseregels, implementatiescripts en technische documentatie. Privéreferenties, klantgegevens en productiegeheimen worden nooit gepubliceerd.",
    stackTitle: "Technologie die je kunt controleren",
    stack: ["React 19 + Vite", "Firebase Authentication en Realtime Database", "Cloudflare Workers, KV en D1", "Stripe-functies en webhooks"],
    licenseTitle: "Een duidelijke open-sourcelicentie",
    licenseText: "Apache 2.0 staat commercieel gebruik, wijzigingen en distributie toe en bevat een uitdrukkelijke patentlicentie. Kopieën en afgeleide werken moeten de licentie en vereiste kennisgevingen behouden.",
    licenseButton: "Lees de Apache 2.0-licentie",
    faqTitle: "Vragen over open source",
    faqs: [
      { question: "Is Link My App echt open source?", answer: "Ja. De officiële repository is openbaar en het project heeft een Apache 2.0-licentie." },
      { question: "Kan ik het zelf hosten?", answer: "Ja. De repository beschrijft de React-, Firebase- en Cloudflare-configuratie voor je eigen implementatie." },
      { question: "Moet ik het zelf hosten?", answer: "Nee. Je kunt de gehoste versie op link-my.app gebruiken zonder infrastructuur te beheren." },
      { question: "Mag een bedrijf de code gebruiken?", answer: "Ja. Apache 2.0 staat commercieel gebruik, wijzigingen en distributie toe als de voorwaarden worden nageleefd." },
    ],
    ctaTitle: "Eén smartlink met controleerbare code",
    ctaText: "Begin met de gehoste versie of bekijk de repository en implementeer Link My App op jouw manier.",
  },
  ar: {
    metaTitle: "رابط ذكي مفتوح المصدر لـ App Store وGoogle Play",
    metaDescription: "أنشئ أو استضف رابطا ذكيا مفتوح المصدر بترخيص Apache 2.0 لـ App Store وGoogle Play والويب وQR وتحليلات النقرات.",
    title: "الرابط الذكي مفتوح المصدر لـ App Store وGoogle Play",
    intro: "يجمع Link My App روابط App Store وGoogle Play والموقع البديل في رابط واحد. الشفرة المصدرية كاملة ومتاحة بترخيص Apache 2.0، ويمكنك استخدام الخدمة المستضافة أو نشرها على بنيتك الخاصة.",
    repoButton: "عرض الشفرة المصدرية",
    createButton: "إنشاء رابط ذكي مجاني",
    facts: [
      { title: "مستودع عام", text: "راجع الشفرة وتابع التغييرات وأبلغ عن المشكلات وساهم عبر GitHub." },
      { title: "Apache 2.0", text: "استخدم المشروع وعدله وأعد توزيعه مع الحفاظ على الترخيص والإشعارات." },
      { title: "قابل للاستضافة الذاتية", text: "انشر تطبيق React وخدمات Firebase وطبقة التحويل في Cloudflare بنفسك." },
      { title: "نسخة مستضافة", text: "استخدم link-my.app فورا من دون إدارة خوادم أو بنية تحويل." },
    ],
    choiceTitle: "استخدمه بالطريقة المناسبة لك",
    choiceIntro: "المنتج العام والمستودع يحلان المشكلة نفسها: رابط تنزيل واحد لكل جهاز.",
    hostedTitle: "مستضاف بواسطة Link My App",
    hostedText: "أنشئ روابط ذكية ورموز QR خلال دقائق. نتولى التحويلات ولوحة التحكم والتحليلات.",
    selfHostedTitle: "انشره بنفسك",
    selfHostedText: "انسخ المستودع واربط حسابي Firebase وCloudflare واحتفظ بالتحكم في النشر والنطاق والبيانات.",
    howTitle: "ما الذي يتضمنه المشروع مفتوح المصدر",
    steps: [
      { title: "توجيه ذكي", text: "يكتشف iPhone وAndroid والكمبيوتر ويرسل كل زائر إلى الوجهة الصحيحة." },
      { title: "لوحة تحكم للمنشئين", text: "أنشئ الروابط الذكية وQR والمصادر والحملات وعدلها وأوقفها وقس نتائجها." },
      { title: "بنية جاهزة للإنتاج", text: "React وVite للواجهة، وFirebase للمصادقة والبيانات، وCloudflare Workers على الحافة." },
    ],
    transparencyTitle: "تطوير علني",
    transparencyText: "يحتوي المستودع على التطبيق وWorker التحويل وقواعد قاعدة البيانات ونصوص النشر والوثائق التقنية. لا تنشر بيانات الدخول الخاصة أو بيانات العملاء أو أسرار الإنتاج أبدا.",
    stackTitle: "تقنيات يمكنك مراجعتها",
    stack: ["React 19 + Vite", "Firebase Authentication وRealtime Database", "Cloudflare Workers وKV وD1", "وظائف Stripe وWebhooks"],
    licenseTitle: "ترخيص مفتوح المصدر واضح",
    licenseText: "يسمح Apache 2.0 بالاستخدام التجاري والتعديل والتوزيع ويتضمن منحة صريحة لبراءات الاختراع. يجب أن تحتفظ النسخ والأعمال المشتقة بالترخيص والإشعارات المطلوبة.",
    licenseButton: "قراءة ترخيص Apache 2.0",
    faqTitle: "أسئلة حول المصدر المفتوح",
    faqs: [
      { question: "هل Link My App مفتوح المصدر حقا؟", answer: "نعم. المستودع الرسمي عام والمشروع منشور بترخيص Apache 2.0." },
      { question: "هل يمكنني استضافته بنفسي؟", answer: "نعم. يشرح المستودع إعداد React وFirebase وCloudflare اللازم لنشرك الخاص." },
      { question: "هل يجب أن أستضيفه بنفسي؟", answer: "لا. يمكنك استخدام النسخة المستضافة على link-my.app من دون إدارة بنية تحتية." },
      { question: "هل يمكن لشركة استخدام الشفرة؟", answer: "نعم. يسمح Apache 2.0 بالاستخدام التجاري والتعديل والتوزيع عند الالتزام بشروطه." },
    ],
    ctaTitle: "رابط ذكي واحد بشفرة يمكنك التحقق منها",
    ctaText: "ابدأ بالنسخة المستضافة أو استكشف المستودع وانشر Link My App بطريقتك.",
  },
  hi: {
    metaTitle: "App Store और Google Play के लिए open-source smart link",
    metaDescription: "Apache 2.0 open-source smart link बनाएं या self-host करें: App Store, Google Play, web fallback, QR code और click analytics.",
    title: "App Store और Google Play के लिए open-source smart link",
    intro: "Link My App, App Store URL, Google Play URL और fallback website को एक साफ लिंक में जोड़ता है। पूरा source code Apache 2.0 के तहत public है, इसलिए hosted service इस्तेमाल करें या अपनी infrastructure पर deploy करें।",
    repoButton: "Source code देखें",
    createButton: "Free smart link बनाएं",
    facts: [
      { title: "Public repository", text: "GitHub पर code देखें, changes follow करें, issues report करें और contribute करें।" },
      { title: "Apache 2.0", text: "License और notices बनाए रखते हुए project इस्तेमाल, modify और redistribute करें।" },
      { title: "Self-hostable", text: "React app, Firebase services और Cloudflare redirect layer खुद deploy करें।" },
      { title: "Hosted version", text: "Servers या redirect infrastructure manage किए बिना link-my.app तुरंत इस्तेमाल करें।" },
    ],
    choiceTitle: "अपने तरीके से इस्तेमाल करें",
    choiceIntro: "Public product और repository एक ही समस्या हल करते हैं: हर device के लिए एक app-download URL।",
    hostedTitle: "Link My App द्वारा hosted",
    hostedText: "कुछ मिनटों में smart links और QR codes बनाएं। Redirects, dashboard और analytics हम चलाते हैं।",
    selfHostedTitle: "खुद deploy करें",
    selfHostedText: "Repository clone करें, अपने Firebase और Cloudflare accounts जोड़ें और deployment, domain व data पर control रखें।",
    howTitle: "Open-source project में क्या शामिल है",
    steps: [
      { title: "Smart routing", text: "iPhone, Android और desktop पहचानकर हर visitor को सही destination पर भेजता है।" },
      { title: "Creator dashboard", text: "Smart links, QR codes, sources और campaigns बनाएं, edit, pause और measure करें।" },
      { title: "Production architecture", text: "Frontend पर React और Vite, authentication व data के लिए Firebase और edge पर Cloudflare Workers।" },
    ],
    transparencyTitle: "Public development",
    transparencyText: "Repository में application, redirect Worker, database rules, deployment scripts और technical documentation हैं। Private credentials, customer data और production secrets कभी public नहीं किए जाते।",
    stackTitle: "ऐसी technology जिसे आप जांच सकते हैं",
    stack: ["React 19 + Vite", "Firebase Authentication और Realtime Database", "Cloudflare Workers, KV और D1", "Stripe functions और webhooks"],
    licenseTitle: "स्पष्ट open-source license",
    licenseText: "Apache 2.0 commercial use, modification और distribution की अनुमति देता है और explicit patent grant शामिल करता है। Copies और derivative works में license व जरूरी notices रखना होता है।",
    licenseButton: "Apache 2.0 license पढ़ें",
    faqTitle: "Open-source सवाल",
    faqs: [
      { question: "क्या Link My App सच में open source है?", answer: "हां। Official repository public है और project Apache 2.0 license के तहत जारी है।" },
      { question: "क्या मैं इसे self-host कर सकता हूं?", answer: "हां। Repository में React, Firebase और Cloudflare setup की documentation है।" },
      { question: "क्या self-host करना जरूरी है?", answer: "नहीं। Infrastructure manage किए बिना link-my.app का hosted version इस्तेमाल कर सकते हैं।" },
      { question: "क्या कोई company code इस्तेमाल कर सकती है?", answer: "हां। Apache 2.0 की शर्तों का पालन करके commercial use, modification और distribution संभव है।" },
    ],
    ctaTitle: "एक smart link, code जिसे आप verify कर सकते हैं",
    ctaText: "Hosted version से शुरू करें या repository देखें और Link My App अपने तरीके से deploy करें।",
  },
};

export function getOpenSourceContent(language = "en") {
  return openSourceContent[language] || openSourceContent.en;
}
