export const useCaseHubRoutes = {
  en: "/use-cases",
  es: "/casos-de-uso",
  fr: "/cas-d-usage",
  ja: "/use-cases",
  de: "/anwendungsfaelle",
  pt: "/casos-de-uso",
  it: "/casi-uso",
  ko: "/use-cases",
  nl: "/toepassingen",
  ar: "/use-cases",
  hi: "/use-cases",
};

export const visibleUseCaseTeasers = [
  {
    id: "ads",
    accent: "from-sky-50 to-white",
    en: { slug: "app-install-ads", label: "Ads", eyebrow: "App install ads" },
    es: { slug: "anuncios-app", label: "Anuncios", eyebrow: "Anuncios de apps" },
    fr: { slug: "publicites-app", label: "Publicites", eyebrow: "Publicites d'app" },
    ja: { slug: "app-install-ads", label: "広告", eyebrow: "アプリ広告" },
    de: { slug: "app-install-ads", label: "Anzeigen", eyebrow: "App-Install-Anzeigen" },
    pt: { slug: "anuncios-app", label: "Anuncios", eyebrow: "Anuncios de apps" },
    it: { slug: "annunci-app", label: "Annunci", eyebrow: "Annunci app" },
    ko: { slug: "app-install-ads", label: "광고", eyebrow: "앱 설치 광고" },
    nl: { slug: "app-install-ads", label: "Advertenties", eyebrow: "App-install ads" },
    ar: { slug: "app-install-ads", label: "الإعلانات", eyebrow: "إعلانات التطبيقات" },
    hi: { slug: "app-install-ads", label: "Ads", eyebrow: "App install ads" },
  },
  {
    id: "ecommerce",
    accent: "from-emerald-50 to-white",
    en: { slug: "ecommerce-apps", label: "Ecommerce", eyebrow: "Ecommerce apps" },
    es: { slug: "apps-ecommerce", label: "Ecommerce", eyebrow: "Apps de ecommerce" },
    fr: { slug: "apps-ecommerce", label: "Ecommerce", eyebrow: "Apps ecommerce" },
    ja: { slug: "ecommerce-app-download-link", label: "ECサイト", eyebrow: "ECアプリ" },
    de: { slug: "ecommerce-app-download-link", label: "Ecommerce", eyebrow: "Ecommerce-Apps" },
    pt: { slug: "link-download-app-ecommerce", label: "Ecommerce", eyebrow: "Apps de ecommerce" },
    it: { slug: "link-download-app-ecommerce", label: "Ecommerce", eyebrow: "App ecommerce" },
    ko: { slug: "ecommerce-app-download-link", label: "이커머스", eyebrow: "이커머스 앱" },
    nl: { slug: "ecommerce-app-downloadlink", label: "E-commerce", eyebrow: "E-commerce apps" },
    ar: { slug: "ecommerce-app-download-link", label: "التجارة الإلكترونية", eyebrow: "تطبيقات التجارة الإلكترونية" },
    hi: { slug: "ecommerce-app-download-link", label: "Ecommerce", eyebrow: "Ecommerce apps" },
  },
  {
    id: "saas",
    accent: "from-blue-50 to-white",
    en: { slug: "saas-apps", label: "SaaS / B2B", eyebrow: "SaaS & B2B apps" },
    es: { slug: "apps-saas", label: "SaaS / B2B", eyebrow: "Apps SaaS y B2B" },
    fr: { slug: "apps-saas", label: "SaaS / B2B", eyebrow: "Apps SaaS et B2B" },
    ja: { slug: "saas-app-download-link", label: "SaaS / B2B", eyebrow: "SaaS・B2Bアプリ" },
    de: { slug: "saas-app-download-link", label: "SaaS", eyebrow: "SaaS und B2B" },
    pt: { slug: "link-download-app-saas", label: "SaaS", eyebrow: "SaaS e B2B" },
    it: { slug: "link-download-app-saas", label: "SaaS", eyebrow: "SaaS e B2B" },
    ko: { slug: "saas-app-download-link", label: "SaaS", eyebrow: "SaaS 및 B2B" },
    nl: { slug: "saas-app-downloadlink", label: "SaaS", eyebrow: "SaaS en B2B" },
    ar: { slug: "saas-app-download-link", label: "SaaS", eyebrow: "SaaS وB2B" },
    hi: { slug: "saas-app-download-link", label: "SaaS", eyebrow: "SaaS और B2B" },
  },
  {
    id: "restaurants",
    accent: "from-amber-50 to-white",
    en: { slug: "restaurant-apps", label: "Restaurants", eyebrow: "Restaurant apps" },
    es: { slug: "apps-restaurantes", label: "Restaurantes", eyebrow: "Apps de restaurantes" },
    fr: { slug: "apps-restauration", label: "Restauration", eyebrow: "Apps restauration" },
    ja: { slug: "restaurant-app-download-link", label: "飲食店", eyebrow: "飲食店アプリ" },
    de: { slug: "restaurant-app-download-link", label: "Restaurants", eyebrow: "Restaurants und Hospitality" },
    pt: { slug: "qr-code-app-restaurante", label: "Restaurantes", eyebrow: "Restaurantes e hospitality" },
    it: { slug: "qr-code-app-ristorante", label: "Ristoranti", eyebrow: "Ristoranti e hospitality" },
    ko: { slug: "restaurant-app-qr-code", label: "레스토랑", eyebrow: "레스토랑 및 hospitality" },
    nl: { slug: "restaurant-app-qr-code", label: "Restaurants", eyebrow: "Restaurants en hospitality" },
    ar: { slug: "restaurant-app-qr-code", label: "المطاعم", eyebrow: "المطاعم والضيافة" },
    hi: { slug: "restaurant-app-qr-code", label: "Restaurants", eyebrow: "Restaurants और hospitality" },
  },
  {
    id: "fitness",
    accent: "from-pink-50 to-white",
    en: { slug: "fitness-apps", label: "Fitness", eyebrow: "Fitness & gym apps" },
    es: { slug: "apps-fitness", label: "Fitness", eyebrow: "Apps de fitness y gimnasios" },
    fr: { slug: "apps-fitness", label: "Fitness", eyebrow: "Apps fitness et salles de sport" },
    ja: { slug: "fitness-app-download-link", label: "フィットネス", eyebrow: "フィットネス・ジムアプリ" },
    de: { slug: "fitness-app-download-link", label: "Fitness", eyebrow: "Fitness und Wellness" },
    pt: { slug: "link-download-app-fitness", label: "Fitness", eyebrow: "Fitness e bem-estar" },
    it: { slug: "link-download-app-fitness", label: "Fitness", eyebrow: "Fitness e benessere" },
    ko: { slug: "fitness-app-download-link", label: "피트니스", eyebrow: "피트니스 및 wellness" },
    nl: { slug: "fitness-app-downloadlink", label: "Fitness", eyebrow: "Fitness en wellness" },
    ar: { slug: "fitness-app-download-link", label: "اللياقة", eyebrow: "اللياقة وwellness" },
    hi: { slug: "fitness-app-download-link", label: "Fitness", eyebrow: "Fitness और wellness" },
  },
  {
    id: "agencies",
    accent: "from-slate-50 to-white",
    en: { slug: "for-agencies", label: "Agencies", eyebrow: "For agencies and partners" },
    es: { slug: "para-agencias", label: "Agencias", eyebrow: "Para agencias y partners" },
    fr: { slug: "pour-agences", label: "Agences", eyebrow: "Pour agences et partenaires" },
    ja: { slug: "for-agencies", label: "代理店", eyebrow: "代理店・パートナー向け" },
    de: { slug: "fuer-agenturen", label: "Agenturen", eyebrow: "Fur Agenturen und Partner" },
    pt: { slug: "para-agencias", label: "Agencias", eyebrow: "Para agencias e parceiros" },
    it: { slug: "per-agenzie", label: "Agenzie", eyebrow: "Per agenzie e partner" },
    ko: { slug: "for-agencies", label: "에이전시", eyebrow: "에이전시 및 파트너용" },
    nl: { slug: "voor-agencies", label: "Agencies", eyebrow: "Voor agencies en partners" },
    ar: { slug: "for-agencies", label: "الوكالات", eyebrow: "للوكالات والشركاء" },
    hi: { slug: "for-agencies", label: "Agencies", eyebrow: "Agencies और partners" },
  },
];

export function teaserNichePath(nicheId, language = "en") {
  const niche = visibleUseCaseTeasers.find((candidate) => candidate.id === nicheId);
  const hub = useCaseHubRoutes[language] || useCaseHubRoutes.en;
  if (!niche) return hub;
  const slug = niche[language]?.slug || niche.en.slug;
  return `${hub}/${slug}`;
}
